<?php
namespace App\Models\Admin\StudentData;

use Illuminate\Database\Eloquent\Model;

class StudentCandidate extends Model
{
	protected $table = "tb_calonsiswa";
    protected $fillable = [
		'KD','REF_PERUSAHAAN','REF_SALES','NAMA','JK','KOTA_KELAHIRAN','TGL_LAHIR','NEGARA','ALAMAT','DUSUN','RT_RW','DESA_KELURAHAN','KOTA','POSTAL_CODE','AGAMA','KONTAK',
		'INSTAGRAM','EMAIL','KEWARGANEGARAAN','REF_KTP','REF_PASPOR','TEST_MODULE','TGL_TEST','TGL_SIMULASI','TINGKAT_PEKERJAAN','SEKTOR_PEKERJAAN','TINGKAT_PENDIDIKAN','UNIVERSITAS_TERAKHIR','JURUSAN','LAMA_BELAJAR_INGGRIS','NEGARA_TUJUAN','ALASAN','TGL_BERLAKU_PASPOR','AMBIL_GELAR','AMBIL_JURUSAN','REF_UNIVERSITAS','BAHASA_SEHARI_HARI','KEBUTUHAN_KHUSUS','PENERIMA_KPS','LAYAK_PIP','PENERIMA_KIP','PATH_KTP','PATH_PASPOR','PATH_PAYMENT'
	];
	
}
