<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
  @include('includes.head')
  @stack('head-script')
  <!-- Fonts -->
  <!-- Styles -->
</head>
<body>
  @yield('modal')
  <div class="col-sm-12">
    <header class="row clearfix">
      <div class="col-md-2 logo-wrapper">
       <a href="/"><img src="{{asset('/img/logo lama.png')}}" class="logo"></a>
     </div>
     <div class="col-md-10">
      <div class="row">
        <div class="col-md-12 menu">
         @menu('navigation-bar')
       </div>
     </div>
   </div>
   @include('includes.mobile-nav')
 </header>

 <div id="main" class="row">
  <div class="popup-overlay"></div>
  @yield('content')
</div>

<script src="{{asset('/js/app.js')}}"></script>
<script src="{{asset('js/mega-menu/megamenu.js')}}"></script>

<!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>-->
<script src="{{asset('/js/slick.js')}}"></script>
<!--<script src="{{asset('/js/toggle-nav.js')}}" type="text/javascript"></script>-->
<script src="https://cdn.jsdelivr.net/npm/vanilla-lazyload@12.0.0/dist/lazyload.min.js"></script>

@stack('more-script')
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-149158649-1"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
<script>
  window.Modernizr || document.write('<script src="js/vendor/modernizr-2.8.3.min.js"><\/script>')
</script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-149158649-1');
</script>
<script type="text/javascript">
//document.addEventListener('contextmenu',event => event.preventDefault());
function mobile_menu(x){
  x.classList.toggle("change");
}
</script>

<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
  [ {
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Immigration",
  "image" : "https://bestpartnereducation.com/public/img/logo%20lama.png",
  "telephone" : "(0561) 8172583",
  "address" : {
  "@type" : "PostalAddress",
  "streetAddress" : "Jl. Prof Dr. Hamka No 29 – 30 (Depan Gg. Nilam 3), Sungai Jawi,",
  "addressLocality" : "Kota Pontianak",
  "addressRegion" : "Kalimantan Barat",
  "addressCountry" : "Indonesia",
  "postalCode" : "78115"
},
"openingHoursSpecification" : {
"@type" : "OpeningHoursSpecification",
"opens" : "Please insert valid ISO 8601 date/time here. Examples: 2015-07-27 or 2015-07-27T15:30",
"closes" : "Please insert valid ISO 8601 date/time here. Examples: 2015-07-27 or 2015-07-27T15:30"
},
"review" : [ {
"@type" : "Review",
"author" : {
"@type" : "Person",
"name" : "Vianey Priscilla"
},
"reviewBody" : "Sangat direkomendasi kan jika ingin test IELTS. Harga terjangkau, free simulasi, ruangan memadai, guru terlatih. Menyedikan kelas persiapan IELTS &amp; test IELTS setiap bulan ! Sukses trus buat Best Partner Pontianak 👍�🏻�"
}, {
"@type" : "Review",
"author" : {
"@type" : "Person",
"name" : "Endy Vandrea"
},
"reviewBody" : "Sir Egi orang nya friendly ketika diajarin dia ,ketika kita tidak mengerti dia tetap membantu kita. Walaupun tidak di jam les kita tanya sesuatu dia membantu kita , But when he have a time he will respond it and they’re said to me about my English speaking  be better. When we’re tired or down he wil help and motivated  us."
} ]
}, {
"@context" : "http://schema.org",
"@type" : "LocalBusiness",
"name" : "IELTS Preparation & Test",
"image" : "https://bestpartnereducation.com/public/img/logo%20lama.png",
"telephone" : "(0561) 8172583",
"address" : {
"@type" : "PostalAddress",
"streetAddress" : "Jl. Prof Dr. Hamka No 29 – 30 (Depan Gg. Nilam 3), Sungai Jawi,",
"addressLocality" : "Kota Pontianak",
"addressRegion" : "Kalimantan Barat",
"addressCountry" : "Indonesia",
"postalCode" : "78115"
},
"openingHoursSpecification" : {
"@type" : "OpeningHoursSpecification",
"opens" : "Please insert valid ISO 8601 date/time here. Examples: 2015-07-27 or 2015-07-27T15:30",
"closes" : "Please insert valid ISO 8601 date/time here. Examples: 2015-07-27 or 2015-07-27T15:30"
},
"review" : [ {
"@type" : "Review",
"author" : {
"@type" : "Person",
"name" : "Vianey Priscilla"
},
"reviewBody" : "Sangat direkomendasi kan jika ingin test IELTS. Harga terjangkau, free simulasi, ruangan memadai, guru terlatih. Menyedikan kelas persiapan IELTS &amp; test IELTS setiap bulan ! Sukses trus buat Best Partner Pontianak 👍�🏻�"
}, {
"@type" : "Review",
"author" : {
"@type" : "Person",
"name" : "Endy Vandrea"
},
"reviewBody" : "Sir Egi orang nya friendly ketika diajarin dia ,ketika kita tidak mengerti dia tetap membantu kita. Walaupun tidak di jam les kita tanya sesuatu dia membantu kita , But when he have a time he will respond it and they’re said to me about my English speaking  be better. When we’re tired or down he wil help and motivated  us."
} ]
}, {
"@context" : "http://schema.org",
"@type" : "LocalBusiness",
"name" : "Consultation",
"image" : "https://bestpartnereducation.com/public/img/logo%20lama.png",
"telephone" : "(0561) 8172583",
"address" : {
"@type" : "PostalAddress",
"streetAddress" : "Jl. Prof Dr. Hamka No 29 – 30 (Depan Gg. Nilam 3), Sungai Jawi,",
"addressLocality" : "Kota Pontianak",
"addressRegion" : "Kalimantan Barat",
"addressCountry" : "Indonesia",
"postalCode" : "78115"
},
"openingHoursSpecification" : {
"@type" : "OpeningHoursSpecification",
"opens" : "Please insert valid ISO 8601 date/time here. Examples: 2015-07-27 or 2015-07-27T15:30",
"closes" : "Please insert valid ISO 8601 date/time here. Examples: 2015-07-27 or 2015-07-27T15:30"
},
"review" : [ {
"@type" : "Review",
"author" : {
"@type" : "Person",
"name" : "Vianey Priscilla"
},
"reviewBody" : "Sangat direkomendasi kan jika ingin test IELTS. Harga terjangkau, free simulasi, ruangan memadai, guru terlatih. Menyedikan kelas persiapan IELTS &amp; test IELTS setiap bulan ! Sukses trus buat Best Partner Pontianak 👍�🏻�"
}, {
"@type" : "Review",
"author" : {
"@type" : "Person",
"name" : "Endy Vandrea"
},
"reviewBody" : "Sir Egi orang nya friendly ketika diajarin dia ,ketika kita tidak mengerti dia tetap membantu kita. Walaupun tidak di jam les kita tanya sesuatu dia membantu kita , But when he have a time he will respond it and they’re said to me about my English speaking  be better. When we’re tired or down he wil help and motivated  us."
} ]
}, {
"@context" : "http://schema.org",
"@type" : "LocalBusiness",
"name" : "TOEFL Preparation & Test",
"image" : "https://bestpartnereducation.com/public/img/logo%20lama.png",
"telephone" : "(0561) 8172583",
"address" : {
"@type" : "PostalAddress",
"streetAddress" : "Jl. Prof Dr. Hamka No 29 – 30 (Depan Gg. Nilam 3), Sungai Jawi,",
"addressLocality" : "Kota Pontianak",
"addressRegion" : "Kalimantan Barat",
"addressCountry" : "Indonesia",
"postalCode" : "78115"
},
"openingHoursSpecification" : {
"@type" : "OpeningHoursSpecification",
"opens" : "Please insert valid ISO 8601 date/time here. Examples: 2015-07-27 or 2015-07-27T15:30",
"closes" : "Please insert valid ISO 8601 date/time here. Examples: 2015-07-27 or 2015-07-27T15:30"
},
"review" : [ {
"@type" : "Review",
"author" : {
"@type" : "Person",
"name" : "Vianey Priscilla"
},
"reviewBody" : "Sangat direkomendasi kan jika ingin test IELTS. Harga terjangkau, free simulasi, ruangan memadai, guru terlatih. Menyedikan kelas persiapan IELTS &amp; test IELTS setiap bulan ! Sukses trus buat Best Partner Pontianak 👍�🏻�"
}, {
"@type" : "Review",
"author" : {
"@type" : "Person",
"name" : "Endy Vandrea"
},
"reviewBody" : "Sir Egi orang nya friendly ketika diajarin dia ,ketika kita tidak mengerti dia tetap membantu kita. Walaupun tidak di jam les kita tanya sesuatu dia membantu kita , But when he have a time he will respond it and they’re said to me about my English speaking  be better. When we’re tired or down he wil help and motivated  us."
} ]
}, {
"@context" : "http://schema.org",
"@type" : "LocalBusiness",
"name" : "Accommodation & Transportation",
"image" : "https://bestpartnereducation.com/public/img/logo%20lama.png",
"telephone" : "(0561) 8172583",
"address" : {
"@type" : "PostalAddress",
"streetAddress" : "Jl. Prof Dr. Hamka No 29 – 30 (Depan Gg. Nilam 3), Sungai Jawi,",
"addressLocality" : "Kota Pontianak",
"addressRegion" : "Kalimantan Barat",
"addressCountry" : "Indonesia",
"postalCode" : "78115"
},
"openingHoursSpecification" : {
"@type" : "OpeningHoursSpecification",
"opens" : "Please insert valid ISO 8601 date/time here. Examples: 2015-07-27 or 2015-07-27T15:30",
"closes" : "Please insert valid ISO 8601 date/time here. Examples: 2015-07-27 or 2015-07-27T15:30"
},
"review" : [ {
"@type" : "Review",
"author" : {
"@type" : "Person",
"name" : "Vianey Priscilla"
},
"reviewBody" : "Sangat direkomendasi kan jika ingin test IELTS. Harga terjangkau, free simulasi, ruangan memadai, guru terlatih. Menyedikan kelas persiapan IELTS &amp; test IELTS setiap bulan ! Sukses trus buat Best Partner Pontianak 👍�🏻�"
}, {
"@type" : "Review",
"author" : {
"@type" : "Person",
"name" : "Endy Vandrea"
},
"reviewBody" : "Sir Egi orang nya friendly ketika diajarin dia ,ketika kita tidak mengerti dia tetap membantu kita. Walaupun tidak di jam les kita tanya sesuatu dia membantu kita , But when he have a time he will respond it and they’re said to me about my English speaking  be better. When we’re tired or down he wil help and motivated  us."
} ]
}, {
"@context" : "http://schema.org",
"@type" : "LocalBusiness",
"name" : "Study Tour",
"image" : "https://bestpartnereducation.com/public/img/logo%20lama.png",
"telephone" : "(0561) 8172583",
"address" : {
"@type" : "PostalAddress",
"streetAddress" : "Jl. Prof Dr. Hamka No 29 – 30 (Depan Gg. Nilam 3), Sungai Jawi,",
"addressLocality" : "Kota Pontianak",
"addressRegion" : "Kalimantan Barat",
"addressCountry" : "Indonesia",
"postalCode" : "78115"
},
"openingHoursSpecification" : {
"@type" : "OpeningHoursSpecification",
"opens" : "Please insert valid ISO 8601 date/time here. Examples: 2015-07-27 or 2015-07-27T15:30",
"closes" : "Please insert valid ISO 8601 date/time here. Examples: 2015-07-27 or 2015-07-27T15:30"
},
"review" : [ {
"@type" : "Review",
"author" : {
"@type" : "Person",
"name" : "Vianey Priscilla"
},
"reviewBody" : "Sangat direkomendasi kan jika ingin test IELTS. Harga terjangkau, free simulasi, ruangan memadai, guru terlatih. Menyedikan kelas persiapan IELTS &amp; test IELTS setiap bulan ! Sukses trus buat Best Partner Pontianak 👍�🏻�"
}, {
"@type" : "Review",
"author" : {
"@type" : "Person",
"name" : "Endy Vandrea"
},
"reviewBody" : "Sir Egi orang nya friendly ketika diajarin dia ,ketika kita tidak mengerti dia tetap membantu kita. Walaupun tidak di jam les kita tanya sesuatu dia membantu kita , But when he have a time he will respond it and they’re said to me about my English speaking  be better. When we’re tired or down he wil help and motivated  us."
} ]
} ]
</script>


<!-- Production version -->
<script src="https://unpkg.com/@popperjs/core@2"></script>
<!--Start of Tawk.to Script
<script type="text/javascript">
  var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
  (function(){
    var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
    s1.async=true;
    s1.src='https://embed.tawk.to/5e7da78635bcbb0c9aaae552/default';
    s1.charset='UTF-8';
    s1.setAttribute('crossorigin','*');
    s0.parentNode.insertBefore(s1,s0);
  })();
</script>
End of Tawk.to Script-->
<!-- </body></html> -->
</body>
</html>
